# Generated by Django 2.2.4 on 2019-08-22 18:14

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20190822_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity_change', models.IntegerField()),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductSKU')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
