# Generated by Django 2.2.4 on 2019-08-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlog',
            name='log_type',
            field=models.CharField(choices=[('change', 'change'), ('empty', 'empty')], default='change', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartlog',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductSKU'),
        ),
        migrations.AlterField(
            model_name='cartlog',
            name='quantity_change',
            field=models.IntegerField(default=0),
        ),
    ]
