# Generated by Django 2.2.4 on 2019-08-20 19:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='sku_code',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='value',
        ),
        migrations.CreateModel(
            name='ProductPropertyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(max_length=16)),
                ('sku_code', models.CharField(max_length=3)),
                ('product_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductProperty')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
