# Generated by Django 2.2.4 on 2019-08-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190820_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='properties',
            field=models.ManyToManyField(to='products.ProductPropertyValues'),
        ),
    ]
